on:
  pull_request_target:
    types:
      - closed
    branches:
      - "release"
    paths:
      - "data-types.yaml"
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo PR with changes to datatypes.yml was merge into staging
      - run: echo "TMP_SRCDIR=./source" >> $GITHUB_ENV
        shell: bash
      - run: echo "TMP_DSTDIR=./dest" >> $GITHUB_ENV
        shell: bash
      - uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
          path: "${{ env.TMP_SRCDIR }}"
      - run: npm ci
      - uses: actions/checkout@v3
        with:
          path: "${{ env.TMP_DSTDIR }}"
          repository: "kdid/test2"
