name: Open PR in test2 on push
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo PR with changes to datatypes.yml was merge into staging
      - run: echo "TMP_SRCDIR=./source" >> $GITHUB_ENV
        shell: bash
      - run: echo "TMP_DSTDIR=./dest" >> $GITHUB_ENV
        shell: bash
      - uses: actions/checkout@v3
        with:
          path: "${{ env.TMP_SRCDIR }}"
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
          path: "${{ env.TMP_SRCDIR }}"
      - run: npm ci
        working-directory: "${{ env.TMP_SRCDIR }}"
      - run: npx openapi-typescript data-types.yaml --output schema.ts
        working-directory: "${{ env.TMP_SRCDIR }}"
      - uses: actions/checkout@v3
        with:
          path: "${{ env.TMP_DSTDIR }}"
          repository: "kdid/test2"
