name: Open PR in test2 on push
run-name: ${{ github.actor }} has started on push workflow 🚀
on: [push]
jobs:
  Push-Types-To-Exteranl-Repo-Staging:
    runs-on: ubuntu-latest
    environment: testing
    permissions:
      id-token: write
      contents: read
    env:
      TARGET_BRANCH: "release-xyz-branch"
      TMP_SRCDIR: "./source"
      TMP_DSTDIR: "./dest"
      TYPES_REPO: "kdid/test2"
    steps:
      - run: |
          echo PR with changes to datatypes.yml was merged into main
      - name: Checkout dc-api-v2
        uses: actions/checkout@v3
        with:
          path: "${{ env.TMP_SRCDIR }}"
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: "${{ env.TMP_SRCDIR }}/package-lock.json"
          node-version: 16.x
          cache: "npm"
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Generate Typescript file
        working-directory: "${{ env.TMP_SRCDIR }}"
        run: |
          npm ci
          npx openapi-typescript data-types.yaml --output schema.ts
      - name: Checkout dcapi-types
        uses: actions/checkout@v3
        with:
          path: ${{ env.TMP_DSTDIR }}
          repository: ${{env.TYPES_REPO}}
      - run: |
          mv -f "${{ env.TMP_SRCDIR }}/schema.ts" "${{ env.TMP_DSTDIR }}/schema.ts"
        shell: bash
      - name: Set GitHub Deploy Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TEST2_DEPLOY_KEY }}
      - working-directory: "${{ env.TMP_DSTDIR }}"
        run: |
          git checkout -b release-xyz-branch
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "v${{ steps.package-version.outputs.current-version}}"
          git push origin HEAD
        shell: bash
