name: Open PR in test2 on push
run-name: ${{ github.actor }} has started on push workflow 🚀
on: [push]
jobs:
  Push-Types-To-Exteranl-Repo-Staging:
    runs-on: ubuntu-latest
    environment: testing
    permissions:
      id-token: write
      contents: read
    env:
      TARGET_BRANCH: "release-xxx-branch"
      TMP_SRCDIR: "./source"
      TMP_DSTDIR: "./dest"
      TYPES_REPO: "kdid/test2"
    steps:
      - run: |
          echo PR with changes to datatypes.yml was merged into main
      - name: Checkout dc-api-v2
        uses: actions/checkout@v3
        with:
          path: "${{ env.TMP_SRCDIR }}"
      - uses: actions/setup-node@v3
        with:
          cache-dependency-path: "${{ env.TMP_SRCDIR }}/package-lock.json"
          node-version: 16.x
          cache: "npm"
      - name: Set short git commit SHA
        working-directory: "${{ env.TMP_SRCDIR }}"
        id: vars
        run: |
          calculatedSha=$(git rev-parse --short ${{ github.sha }})
          echo "::set-output name=short_sha::$calculatedSha"
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: "${{ env.TMP_SRCDIR }}"
      - name: Generate Typescript file
        working-directory: "${{ env.TMP_SRCDIR }}"
        run: |
          npm ci
          npx openapi-typescript data-types.yaml --output schema.ts
      - name: Checkout dcapi-types
        uses: actions/checkout@v3
        with:
          path: ${{ env.TMP_DSTDIR }}
          repository: ${{env.TYPES_REPO}}
      - run: |
          mv -f "${{ env.TMP_SRCDIR }}/schema.ts" "${{ env.TMP_DSTDIR }}/schema.ts"
        shell: bash
      - name: Set GitHub Deploy Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.TEST2_DEPLOY_KEY }}
      - working-directory: "${{ env.TMP_DSTDIR }}"
        run: |
          git checkout -b dcapi-${{ steps.vars.outputs.short_sha }}
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "nulib/dc-api-v2 v${{ steps.package-version.outputs.current-version}} release"
          git push origin HEAD
          echo "GH_TOKEN=${{secrets.TEST2_PR_TOKEN}}" >> $GITHUB_ENV
        shell: bash
      - name: Open nulib/dcapi-client PR
        id: open-types-pr
        working-directory: "${{ env.TMP_DSTDIR }}"
        run: |
          echo 'gh pr create --base main --title "DC API release v${{ steps.package-version.outputs.current-version}}" --body "A new version of `nulib/dc-api-v2` has been released. Please review changes and release a new version of the types package if needed." --reviewer kdid' >> $GITHUB_OUTPUT
        shell: bash
      - name: Create issue
        working-directory: "${{ env.TMP_DSTDIR }}"
        run: |
          gh issue create -t "Update nulib/dcapi-types for API release v${{ steps.package-version.outputs.current-version}} -b "### Description\n\nReview PR: ${{ steps.open-types-pr.outputs.}}" -a @me -l "digital collections", "front end"
        shell: bash
