name: Open PR in test2 on push
run-name: ${{ github.actor }} has started on push workflow 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo PR with changes to datatypes.yml was merged into staging
      - run: echo "TMP_SRCDIR=./source" >> $GITHUB_ENV
        shell: bash
      - run: echo "TMP_DSTDIR=./dest" >> $GITHUB_ENV
        shell: bash
      - name: Checkout dc-api-v2
        uses: actions/checkout@v3
        with:
          path: ${{ env.TMP_SCRDIR }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm ci
      - run: npx openapi-typescript data-types.yaml --output schema.ts
      - name: Checkout dcapi-types
        uses: actions/checkout@v3
        with:
          repository: kdid/test2
          path: ${{ env.TMP_DSTDIR }}
